In [1]:
# Reference : https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [2]:
#1. Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.15.4


In [3]:
#2. How to create a 1D array?
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#3. How to create a boolean array?
#Create a 3×3 numpy array of all True’s
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
#4. How to extract items that satisfy a given condition from 1D array?
#Q. Extract all evevnumbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[::2]

array([0, 2, 4, 6, 8])

In [6]:
# odd number
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [7]:
#5. How to replace items that satisfy a condition with another value in numpy array?
#Q. Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
# 6. How to replace items that satisfy a condition without affecting the original array?
#Q. Replace all odd numbers in arr with -1 without changing arr
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# Method 2 , but here we are creating copy
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = arr.copy()
out[out % 2 == 1] = -1
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
#7. How to reshape an array?
np.arange(10)
np.arange(10).reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Stack

In [11]:
#  8. How to stack two arrays vertically?
#Q. Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
# Method 1:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
# Method 2:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
#Method3:
# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
# 9. How to stack two arrays horizontally?
# Method 1:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
# Method 2:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# np.Tile

In [18]:
#10. How to generate custom sequences in numpy without hardcoding?
#Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
#Repeat elements of an array.
a = np.array([1,2,3])
x = np.repeat(a, 3)

In [19]:
# Construct an array by repeating A the number of times given by reps.
y = np.tile(a, 3)

In [20]:
np.r_[x,y]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# np.intersect1d

In [21]:
#11. How to get the common items between two python numpy arrays?
#Q. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

# np.setdiff1d

In [22]:
#1212. How to remove from one array those items that exist in another?

# Difficulty Level: L2

# Q. From array a remove all items present in array b

# Input:

# a = np.array([1,2,3,4,5])
# b = np.array([5,6,7,8,9])

# Desired Output:

# array([1,2,3,4])

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# From 'a' remove all of 'b'
np.setdiff1d(a,b)
#> array([1, 2, 3, 4])


array([1, 2, 3, 4])

# np.where

In [23]:
# #13. How to get the positions where elements of two arrays match?

# Difficulty Level: L2

# Q. Get the positions where elements of a and b match

# Input:

# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output:

# #> (array([1, 3, 5, 7]),)
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)
#> (array([1, 3, 5, 7]),)

(array([1, 3, 5, 7], dtype=int64),)

In [24]:
# 14. How to extract all numbers between a given range from a numpy array?

# Difficulty Level: L2

# Q. Get all items between 5 and 10 from a.

# Input:

# a = np.array([2, 6, 1, 9, 10, 3, 27])

# Desired Output:

# (array([6, 9, 10]),)
# Method 1
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a > 5) & (a <= 10)]

array([ 6,  9, 10])

In [25]:
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),

array([ 6,  9, 10])

# Find the maximun

In [26]:
# 15. How to make a python function that handles scalars to work on numpy arrays?

# Difficulty Level: L2

# Q. Convert the function maxx that works on two scalars, to work on two arrays.

# Input:

# def maxx(x, y):
#     """Get the maximum of two items"""
#     if x >= y:
#         return x
#     else:
#         return y

# maxx(1, 5)
# #> 5

def maxx(x, y):
    """Get the maximum of two items"""
    if (x >= y):
        return x
    else:
        return y

print(maxx(1, 10))
print(maxx([1,2],[5,4]))
print(maxx(5, 1))
print(maxx([5,6],[5,4]))

10
[5, 4]
5
[5, 6]


In [27]:
# we will get which one is max array
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

array([6., 7., 9., 8., 9., 7., 5.])

# Swap the column

In [28]:
# 16. How to swap two columns in a 2d numpy array?

# Difficulty Level: L2

# Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# Reverse Row and columns

In [30]:
# 18. How to reverse the rows of a 2D array?

# Difficulty Level: L2

# Q. Reverse the rows of a 2D array arr.

# # Input
# arr = np.arange(9).reshape(3,3)

# Show Solution

# Input
arr = np.arange(9).reshape(3,3)
print(arr)
# Solution
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [31]:
# 19. How to reverse the columns of a 2D array?

# Difficulty Level: L2

# Q. Reverse the columns of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# Customize the display end value

In [33]:
# 20. How to create a 2D array containing random floats between 5 and 10?

# Difficulty Level: L2

# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Show Solution


In [34]:
np.random.randint(5,10,15).reshape(5,3)

array([[8, 7, 5],
       [6, 6, 7],
       [7, 8, 9],
       [9, 7, 6],
       [8, 5, 6]])

In [35]:
#How to create a 2D array containing random floats between 5 and 10?
# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[9.29882854 9.77915187 7.8393439 ]
 [5.96263625 8.53285002 9.00715403]
 [5.88601031 7.09028802 9.37106492]
 [7.10023734 5.64607557 8.21281635]
 [5.39477049 9.02307912 6.21918461]]


In [36]:
# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[9.09734195 6.96501904 7.43253412]
 [7.00316696 6.84811338 8.25996202]
 [9.71034121 9.63463713 9.66722069]
 [5.80278619 7.26744569 9.36510408]
 [8.83094275 5.85841047 7.13054577]]


In [37]:
# 21. How to print only 3 decimal places in python numpy array?

# Difficulty Level: L1

# Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [38]:
np.set_printoptions(precision=3)
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[6.671 6.6   6.149]
 [9.369 8.886 7.167]
 [5.832 5.94  5.327]
 [8.36  6.689 9.41 ]
 [9.997 7.983 7.837]]


In [39]:
# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

# Difficulty Level: L1

# Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Input:

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e2
rand_arr


array([[5.434e-03, 2.784e-03, 4.245e-03],
       [8.448e-03, 4.719e-05, 1.216e-03],
       [6.707e-03, 8.259e-03, 1.367e-03]])

In [40]:
# Desired Output:

# #> array([[ 0.000543,  0.000278,  0.000425],
# #>        [ 0.000845,  0.000005,  0.000122],
# #>        [ 0.000671,  0.000826,  0.000137]])

# Reset printoptions to default
np.set_printoptions(precision=False)
np.set_printoptions(suppress=False)
rand_arr

array([[5.e-03, 3.e-03, 4.e-03],
       [8.e-03, 5.e-05, 1.e-03],
       [7.e-03, 8.e-03, 1.e-03]])

In [41]:
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.005434, 0.002784, 0.004245],
       [0.008448, 0.000047, 0.001216],
       [0.006707, 0.008259, 0.001367]])

In [42]:
# 23. How to limit the number of items printed in output of numpy array?

# Difficulty Level: L1

# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

# Input:
a = np.arange(15)
a
# #> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Desired Output:

# #> array([ 0,  1,  2, ..., 12, 13, 14])


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [44]:
# Q. Print the full numpy array a without truncating.

# Input:

# np.set_printoptions(threshold=6)
# a = np.arange(15)
# a
# #> array([ 0,  1,  2, ..., 12, 13, 14])
# Desired Output:

# a
# #> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


In [45]:
np.set_printoptions(threshold=np.nan)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Read Iris data & perfome some operation

In [46]:
# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

# Difficulty Level: L2

# Q. Import the iris dataset keeping the text intact.
# Show Solution

# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]
#> array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
#>        [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
#>        [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

#Since we want to retain the species, a text field, I have set the dtype to object. Had I set dtype=None, a 1d array of tuples would have been returned.

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [47]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=None)
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [48]:
# 26. How to extract a particular column from 1D array of tuples?

# Difficulty Level: L2

# Q. Extract the text column species from the 1D iris imported in previous question.
# Loop through the value & capture first row values
species = np.array([row[0] for row in iris])
# Print 5 values
species[:5]

array([5.1, 4.9, 4.7, 4.6, 5. ])

In [49]:
# 27. How to convert a 1d array of tuples to a 2d numpy array?

# Difficulty Level: L2

# Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field
#Method1
# Loop through the each row & convert as list & while converting as list take first 4 paramter
iris_2d = np.array([row.tolist()[:4] for row in iris])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [50]:
# Alt Method 2: Import only the first 4 columns from source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [51]:
# 28. How to compute the mean, median, standard deviation of a numpy array?

# Difficulty: L1

# Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

In [52]:
np.mean(iris_2d[:,0])

5.843333333333334

In [53]:
np.median(iris_2d[:,0])

5.8

In [54]:
np.std(iris_2d[:,0])

0.8253012917851409

In [55]:
# 29. How to normalize an array so the values range exactly between 0 and 1?

# Difficulty: L2

# Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

# Input:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
# Solution
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
# or 
S = (sepallength - Smin)/sepallength.ptp()  
print(S)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

# Softmax score

In [56]:
# 30. How to compute the softmax score?

# Difficulty Level: L3

# Q. Compute the softmax score of sepallength.

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [57]:
print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

# np.percentile

In [58]:
# 31. How to find the percentile scores of a numpy array?

# Difficulty Level: L1

# Q. Find the 5th and 95th percentile of iris's sepallength

# Solution
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [59]:
# 32. How to insert values at random positions in an array?

# Difficulty Level: L2

# Q. Insert np.nan values at 20 random positions in iris_2d dataset

# Random insert

In [60]:
# Method 1
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
i, j = np.where(iris_2d)

# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan


In [61]:
# Method 2
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [62]:
# Print first 10 rows
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]
